IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'dbo.usp_deleteItem') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE dbo.usp_deleteItem
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE dbo.usp_deleteItem
(
	@Id UNIQUEIDENTIFIER
)
AS 
BEGIN
	BEGIN TRY

		BEGIN TRANSACTION DELETE_TRAN
			UPDATE TblTodo SET  
			IsDeleted = 0, 
			UpdatedDate = GETDATE()
			WHERE ID = @Id
		COMMIT TRANSACTION DELETE_TRAN
	END TRY
	BEGIN CATCH
		IF @@trancount > 0
			ROLLBACK TRANSACTION DELETE_TRAN
	END CATCH
END
GO