IF OBJECT_ID('dbo.usp_getItemById') IS NOT NULL
	SET NOEXEC ON
GO
CREATE PROCEDURE dbo.usp_getItemById
AS RETURN;
GO
SET NOEXEC OFF
GO
ALTER PROCEDURE dbo.usp_getItemById
(
	@Id UNIQUEIDENTIFIER
)
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'
AS BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		BEGIN TRANSACTION 
			SELECT tt.ID, tt.Item, tt.ItemDescription, tt.CreatedDate, tt.UpdatedDate, tt.CompletedDate, tt.Status FROM TblTodo tt WHERE tt.ID = @Id AND tt.IsDeleted <> 0
		COMMIT TRANSACTION
    END TRY
	BEGIN CATCH
		BEGIN TRANSACTION
			INSERT INTO dbo.DB_Errors
			VALUES
		  (
			SUSER_SNAME(),
			ERROR_NUMBER(),
			ERROR_STATE(),
			ERROR_SEVERITY(),
			ERROR_LINE(),
			ERROR_PROCEDURE(),
			ERROR_MESSAGE(),
			GETDATE());
 
		-- Transaction uncommittable
			IF (XACT_STATE()) = -1
				ROLLBACK TRANSACTION
 
		-- Transaction committable
			IF (XACT_STATE()) = 1
				COMMIT TRANSACTION
	END CATCH
END
GO